# FireRFS Configuration Example
# Save this file as config.yaml and customize according to your needs

# Authentication
api_key: YOUR_API_KEY
project_id: YOUR_PROJECT_ID  # Optional

# Scan Configuration
scan_mode: comprehensive  # Options: quick, comprehensive
timeout: 30  # Request timeout in seconds

# Services to Test
services:
  - database    # Firebase Realtime Database
  - firestore   # Cloud Firestore
  - storage     # Cloud Storage
  - functions   # Cloud Functions
  - hosting     # Firebase Hosting
  - auth        # Authentication Service

# Output Configuration
output:
  format: html      # Options: html, json, text
  directory: scan_results
  detailed: true    # Include detailed findings
  data_dump: false  # Extract accessible data

# Advanced Options
advanced:
  retry_attempts: 3
  concurrent_requests: 5
  follow_references: true
  max_depth: 3

# Custom Rules
rules:
  max_severity: critical  # Options: critical, high, medium, low, info
  ignore_warnings: false
  custom_checks:
    - name: api_key_rotation
      enabled: true
      threshold_days: 90
    - name: public_access
      enabled: true
      services:
        - database
        - storage

# Security rules to check
security_rules:
  - public_access
  - authentication
  - data_validation
  - rate_limiting
  - cors_configuration

# Custom vulnerability checks
custom_checks:
  - name: sensitive_data_exposure
    pattern: "(?i)(password|secret|key|token)"
    severity: high
  
  - name: insecure_configuration
    pattern: "(?i)(test|debug|development)"
    severity: medium

# Report configuration
reporting:
  format: html
  include_metadata: true
  save_raw_results: true
  output_directory: "./reports"

# Logging configuration
logging:
  level: INFO
  file: firerfs.log
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"

# Network settings
network:
  timeout: 10
  max_retries: 3
  proxy:
    enabled: false
    http: "http://proxy.example.com:8080"
    https: "https://proxy.example.com:8080"

# Authentication
auth:
  service_account: null  # Path to service account JSON file
  api_key: null  # Firebase API key
  project_id: null  # Firebase project ID 